### ISSUE TITLE
update-vim-plugins

### ISSUE THREAD

**Issue by su8** [brianbuccola/scripts#1]
Instead using simple pull, you could also:

```bash
git fetch --all
git reset --hard
git pull origin master
```

**Comment by su8** [comment]
Also test wheater the folder exists and if not clone with `--depth 1`.

**Comment by brianbuccola** [comment]
Since we're only calling `cd` on whatever is captured by the wildcard `*` (`for d in *;`), how could it be that the folder doesn't exist? If it didn't exist, it wouldn't be part of the expansion of `*`. Or maybe I'm misunderstanding what you meant.

By the way, I've since migrated to [vim-plug](https://github.com/junegunn/vim-plug), which provides a `:PluginUpdate` command, so I haven't used this script in a long time. I may at some point get rid of vim-plug now that vim 8 has builtin package/runtime management.
